[project]
name = "sahwa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.9.21"
dependencies = [
    "jupyter>=1.1.1",
    "ipykernel>=6.0.3",
    "pysnptools==0.5.3",
    "numpy<=1.26.0",
]
